import { ProviderManifestSchema, type ProviderManifest } from "./contracts";

export const providerManifests = {
  openai: ProviderManifestSchema.parse({
    id: "openai",
    name: "openai",
    displayName: "OpenAI",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: [
      "briefGeneration",
      "imageGeneration",
      "imageEdit",
      "styleReferenceAnalysis",
      "compositionReferenceAnalysis",
      "healthCheck",
      "costEstimate",
    ],
    modelSlots: {
      concept: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      image: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
      styleReference: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      compositionReference: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      imageEdit: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    },
    imageGeneration: {
      referenceInput: "promptOnly",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: true,
      notes: ["Uses the shared provider-neutral image prompt; reference transport can be upgraded without changing Poster logic."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Primary planned provider for text planning and image generation."],
  }),
  aigocode: ProviderManifestSchema.parse({
    id: "aigocode",
    name: "aigocode-openai-compatible",
    displayName: "AIGoCode",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: [
      "briefGeneration",
      "imageGeneration",
      "imageEdit",
      "styleReferenceAnalysis",
      "compositionReferenceAnalysis",
      "healthCheck",
      "costEstimate",
    ],
    modelSlots: {
      concept: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      image: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1", "dall-e-3"],
      styleReference: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      compositionReference: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1"],
      imageEdit: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    },
    imageGeneration: {
      referenceInput: "promptOnly",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: true,
      notes: ["OpenAI-compatible routing; provider-specific transport should not fork mode logic."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["OpenAI-compatible relay provider for AIGoCode API keys and model-list diagnostics."],
  }),
  google: ProviderManifestSchema.parse({
    id: "google",
    name: "google-ai-studio",
    displayName: "Google AI Studio",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: [
      "briefGeneration",
      "imageGeneration",
      "styleReferenceAnalysis",
      "compositionReferenceAnalysis",
      "healthCheck",
      "costEstimate",
    ],
    modelSlots: {
      concept: ["gemini-2.5-flash", "gemini-2.5-pro"],
      image: ["gemini-3-pro-image-preview", "gemini-2.5-flash-image"],
      styleReference: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-3-pro-image-preview"],
      compositionReference: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-3-pro-image-preview"],
    },
    imageGeneration: {
      referenceInput: "inlineParts",
      localReferenceHandling: "fetchInline",
      promptProfile: "dense",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "dataUrl",
      supportsImageEdit: false,
      notes: ["Uses inline visual reference parts; Poster logic remains shared with other providers."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Google AI Studio Gemini image provider for Nano Banana style generation."],
  }),
  deepseek: ProviderManifestSchema.parse({
    id: "deepseek",
    name: "deepseek",
    displayName: "DeepSeek",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: ["briefGeneration", "healthCheck", "costEstimate"],
    modelSlots: {
      concept: ["deepseek-v4-flash", "deepseek-v4-pro"],
    },
    imageGeneration: {
      referenceInput: "none",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: false,
      notes: ["Planning-only provider; image slots should route elsewhere."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Text planning and reasoning provider. Image output should route to an image-capable provider."],
  }),
  claude: ProviderManifestSchema.parse({
    id: "claude",
    name: "anthropic-claude",
    displayName: "Claude",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: ["briefGeneration", "styleReferenceAnalysis", "compositionReferenceAnalysis", "healthCheck", "costEstimate"],
    modelSlots: {
      concept: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5", "claude-haiku-4-5-20251001", "claude-opus-4-6"],
      styleReference: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5", "claude-haiku-4-5-20251001"],
      compositionReference: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5", "claude-haiku-4-5-20251001"],
    },
    imageGeneration: {
      referenceInput: "none",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: false,
      notes: ["Planning/reference-analysis provider; image slots should route elsewhere."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Claude provider for planning, copy, and visual reference understanding."],
  }),
  qwen: ProviderManifestSchema.parse({
    id: "qwen",
    name: "qwen",
    displayName: "Qwen",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: ["briefGeneration", "imageGeneration", "styleReferenceAnalysis", "compositionReferenceAnalysis", "healthCheck", "costEstimate"],
    modelSlots: {
      concept: ["qwen3.7-max", "qwen3.6-max-preview", "qwen3.6-plus", "qwen3.6-flash"],
      image: ["wan2.7-image-pro", "wan2.7-image", "qwen-image-2.0-pro", "qwen-image-2.0"],
      styleReference: ["qwen3.6-plus", "qwen3.5-flash", "qwen3.5-plus"],
      compositionReference: ["qwen3.6-plus", "qwen3.5-flash", "qwen3.5-plus"],
    },
    imageGeneration: {
      referenceInput: "promptOnly",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: false,
      notes: ["Image-capable provider with shared mode logic; specific image-reference transport can be added here."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Qwen provider for Chinese planning, multimodal reference analysis, and supported image models."],
  }),
  agnes: ProviderManifestSchema.parse({
    id: "agnes",
    name: "agnes-ai",
    displayName: "Agnes AI",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: ["briefGeneration", "imageGeneration", "imageEdit", "healthCheck", "costEstimate"],
    modelSlots: {
      concept: ["agnes-2.0-flash", "agnes-1.5-flash"],
      image: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
      imageEdit: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
    },
    imageGeneration: {
      referenceInput: "extraBodyImage",
      localReferenceHandling: "dataUrlExtraBody",
      promptProfile: "compressed",
      promptMaxChars: 10000,
      textRendering: "low",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: true,
      notes: ["Sends visual references through extra_body.image as URL/Data URI inputs and keeps prompt hierarchy concise."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["OpenAI-style Agnes AI provider for text planning and image generation/editing with URL-based image references."],
  }),
  mimo: ProviderManifestSchema.parse({
    id: "mimo",
    name: "xiaomi-mimo",
    displayName: "小米 MiMo",
    baseUrlRequired: false,
    apiKeyRequired: true,
    capabilities: ["briefGeneration", "styleReferenceAnalysis", "compositionReferenceAnalysis", "healthCheck", "costEstimate"],
    modelSlots: {
      concept: ["mimo-v2.5-pro", "mimo-v2.5", "mimo-v2-pro", "mimo-v2-omni"],
      styleReference: ["mimo-v2-omni"],
      compositionReference: ["mimo-v2-omni"],
    },
    imageGeneration: {
      referenceInput: "none",
      localReferenceHandling: "none",
      promptProfile: "standard",
      promptMaxChars: 12000,
      textRendering: "medium",
      resultDelivery: "urlOrDataUrl",
      supportsImageEdit: false,
      notes: ["OpenAI-compatible chat route for planning; image output should route to an image-capable provider."],
    },
    supportedModes: ["poster", "collab", "announcement", "logo", "icon"],
    notes: ["Xiaomi MiMo OpenAI-compatible provider for brief and scheme generation."],
  }),
} satisfies Record<ProviderManifest["id"], ProviderManifest>;

export const providerManifestList = Object.values(providerManifests);

export function getProviderManifest(providerId: ProviderManifest["id"]): ProviderManifest {
  return providerManifests[providerId];
}
