import {
  BrandKitSchema,
  CharacterProfileSchema,
  ProjectSchema,
  ResultAssetSchema,
  SchemeBriefSchema,
  type ProductionMode,
  type ProviderConfigForm,
} from "../schema/zod";
import {
  createModeFormDefaults,
  createOutputSettingsDefaults,
  createProjectBriefDefaults,
  createProviderConfigDefaults,
  createSloganSettingsDefaults,
} from "../schema/zod-defaults";
import { createBatchQueuePlan } from "../queue/planner";
import { summarizeQueue } from "../queue/contracts";
import {
  StoredArchiveRowSchema,
  StoredAssetRecordSchema,
  WorkspaceModeStateSchema,
  WorkspaceSnapshotSchema,
  type WorkspaceSnapshot,
} from "./contracts";
import { containsUnredactedSecret, redactProviderConfigs } from "./redaction";

const PROJECT_ID = "project-pizza-kitchen";
const WORKSPACE_ID = "workspace-pizza-kitchen";
const CREATED_AT = "2026-05-21T00:00:00.000Z";

const modes: ProductionMode[] = ["poster", "collab", "announcement", "logo", "icon"];

function createSchemes() {
  return modes.map((mode, index) =>
    SchemeBriefSchema.parse({
      id: `scheme-${mode}-01`,
      projectId: PROJECT_ID,
      mode,
      code: `${mode.slice(0, 2).toUpperCase()}-01`,
      title: `${mode} production direction`,
      brief: `A stored ${mode} creative brief for project recovery and archive testing.`,
      slogans: {
        "zh-CN": "从创意到批量出图",
        "en-US": "From brief to batch output",
      },
      promptBlocks: [
        {
          title: "Storage",
          text: "This prompt block is stored as project context, not regenerated by the UI.",
        },
      ],
      lockedFields: index === 1 ? ["characterPlaceholdersOnly", "preventCharacterMerge"] : [],
      outputPresets: ["tiktok", "metaAds"],
      status: index === 0 ? "ready" : "pending",
    }),
  );
}

function createModeStates() {
  return modes.map((mode) =>
    WorkspaceModeStateSchema.parse({
      mode,
      projectBrief: createProjectBriefDefaults(mode),
      outputSettings: createOutputSettingsDefaults(mode),
      sloganSettings: createSloganSettingsDefaults(),
      modeForm: createModeFormDefaults(mode),
      selectedSchemeIds: [`scheme-${mode}-01`],
      updatedAt: CREATED_AT,
    }),
  );
}

function createProviderSettings() {
  const openai: ProviderConfigForm = {
    ...createProviderConfigDefaults("openai"),
    enabled: false,
    apiKey: "",
  };
  const aigocode: ProviderConfigForm = createProviderConfigDefaults("aigocode");
  const google: ProviderConfigForm = createProviderConfigDefaults("google");
  const deepseek: ProviderConfigForm = createProviderConfigDefaults("deepseek");
  const claude: ProviderConfigForm = createProviderConfigDefaults("claude");
  const qwen: ProviderConfigForm = createProviderConfigDefaults("qwen");
  const agnes: ProviderConfigForm = createProviderConfigDefaults("agnes");
  const mimo: ProviderConfigForm = createProviderConfigDefaults("mimo");

  return redactProviderConfigs([openai, aigocode, google, deepseek, claude, qwen, agnes, mimo], { updatedAt: CREATED_AT });
}

export function createMockWorkspaceSnapshot(): WorkspaceSnapshot {
  const project = ProjectSchema.parse({
    id: PROJECT_ID,
    name: "Pizza Kitchen Adventures",
    description:
      "A hybrid cooking management and wilderness hunting game where chef teams gather rare ingredients for VIP guests.",
    genre: "Simulation RPG",
    coreSellingPoints: ["chef squad", "monster ingredients", "restaurant operation"],
    targetAudience: "Casual and mid-core players who enjoy collecting, cooking, and progression.",
    brandKitId: "brand-pizza-kitchen",
    defaultMode: "poster",
  });

  const brandKit = BrandKitSchema.parse({
    id: "brand-pizza-kitchen",
    projectId: PROJECT_ID,
    logos: ["asset-game-logo"],
    primaryColors: ["#F97316", "#2563EB"],
    typographyStyle: "Chunky readable game typography with premium campaign polish.",
    fixedBrandTerms: ["Pizza Kitchen Adventures"],
    bannedElements: ["real-world protected game IP"],
  });

  const assets = [
    StoredAssetRecordSchema.parse({
      id: "asset-game-character",
      projectId: PROJECT_ID,
      role: "gameCharacter",
      label: "Hero chef squad",
      sourceType: "uploaded",
      previewUrl: "https://example.com/assets/hero-chef.png",
      usage: ["input", "reference"],
      storageKey: "projects/project-pizza-kitchen/assets/hero-chef.png",
      mimeType: "image/png",
      byteSize: 2400000,
      checksum: "sha256-hero-chef",
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    }),
    StoredAssetRecordSchema.parse({
      id: "asset-game-logo",
      projectId: PROJECT_ID,
      role: "gameLogo",
      label: "Game logo",
      sourceType: "uploaded",
      previewUrl: "https://example.com/assets/game-logo.png",
      usage: ["input"],
      storageKey: "projects/project-pizza-kitchen/assets/game-logo.png",
      mimeType: "image/png",
      byteSize: 620000,
      checksum: "sha256-game-logo",
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    }),
    StoredAssetRecordSchema.parse({
      id: "asset-poster-composition",
      projectId: PROJECT_ID,
      role: "compositionReference",
      label: "Poster composition reference",
      sourceType: "uploaded",
      previewUrl: "https://example.com/assets/poster-composition.png",
      usage: ["reference"],
      storageKey: "projects/project-pizza-kitchen/assets/poster-composition.png",
      mimeType: "image/png",
      byteSize: 840000,
      checksum: "sha256-poster-composition",
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    }),
  ];

  const characters = [
    CharacterProfileSchema.parse({
      id: "character-hero-chef",
      projectId: PROJECT_ID,
      name: "Hero Chef",
      referenceAssetIds: ["asset-game-character"],
      lockAppearance: true,
      consistencyStrength: 0.82,
    }),
  ];

  const schemes = createSchemes();
  const queuePlans = [
    createBatchQueuePlan({
      projectId: PROJECT_ID,
      mode: "poster",
      providerId: "openai",
      schemeIds: ["scheme-poster-01"],
      imagesPerScheme: 1,
      includeImageEdit: false,
      includeUpscale: true,
      includeBackgroundRemoval: true,
    }),
  ];

  const firstPlan = queuePlans[0];
  if (!firstPlan) throw new Error("Mock workspace snapshot requires a queue plan.");

  const baseResult = ResultAssetSchema.parse({
    id: "result-poster-01",
    projectId: PROJECT_ID,
    schemeId: "scheme-poster-01",
    jobId: firstPlan.job.id,
    mode: "poster",
    width: 1080,
    height: 1920,
    platformPreset: "tiktok",
    language: "en-US",
    model: "gpt-image-2",
    status: "ready",
  });

  const result = {
    ...baseResult,
    taskId: `${firstPlan.job.id}-image-1`,
    providerResultId: "provider-result-poster-01",
    thumbnailUrl: "https://example.com/results/poster-01-thumb.png",
    assetUrl: "https://example.com/results/poster-01.png",
    favorite: true,
    archivedAt: CREATED_AT,
    metadata: { source: "mock-provider" },
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  };

  const snapshot = WorkspaceSnapshotSchema.parse({
    version: "workspace.v1",
    metadata: {
      workspaceId: WORKSPACE_ID,
      ownerId: "user-demo",
      backend: "memory",
      revision: 1,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    activeMode: "poster",
    project,
    brandKit,
    characters,
    assets,
    providerConfigs: createProviderSettings(),
    modeStates: createModeStates(),
    schemes,
    queuePlans,
    queueSummaries: queuePlans.map((plan) => summarizeQueue(plan)),
    referenceAnalyses: [],
    results: [result],
    archiveRows: [
      StoredArchiveRowSchema.parse({
        id: "archive-row-poster-01",
        projectId: PROJECT_ID,
        resultAssetId: result.id,
        title: "Poster campaign result",
        mode: "poster",
        model: "gpt-image-2",
        state: "archived",
        createdAt: CREATED_AT,
        updatedAt: CREATED_AT,
      }),
    ],
  });

  if (containsUnredactedSecret(snapshot)) {
    throw new Error("Mock workspace snapshot contains an unredacted secret.");
  }

  return snapshot;
}
